db:
  image: mongo:3.2
  container_name: quickMongo
web:
  build: .
  command: bash -c "cd /quickshake && npm install && source .secret.sh &&  npm start --"
  volumes:
    - .:/quickshake
  ports:
    - "8888:8888"
  links:
    - db
  container_name: quickShake  